### ISSUE TITLE
Arb * ArbMatrix becomes Matrix{Arb} instead of ArbMatrix

### ISSUE THREAD

**Issue by nanleij** [kalmarek/Arblib.jl#122]
Hi, I came across this issue a few times now, so I thought I would mention it here.
```
julia> Arb(2)*ArbMatrix([1 2; 3 4])
2×2 Matrix{Arb}:
 2.0000000000000000000000000000000000000000000000000000000000000000000000000000  …  4.0000000000000000000000000000000000000000000000000000000000000000000000000000
 6.0000000000000000000000000000000000000000000000000000000000000000000000000000     8.0000000000000000000000000000000000000000000000000000000000000000000000000000
```
So after multiplying a scalar with a matrix things start to break down because you don't have an `ArbMatrix` anymore
My workaround is using `Arblib.addmul!(B,A,c)` or `Arblib.mul!(B,A,c)` depending on the case, but I think this should be added here too because it is a common operation for matrices.  I'm not sure about the types (e.g., how to handle cases like Acb * ArbMatrix except for defining separate functions for them), but without typing something like this would probably suffice:
```
function Base.:(*)(c, A)
    B = similar(A)
    Arblib.mul!(B,A,c)
    B
end
```

**Comment by saschatimme** [comment]
> I'm not sure about the types (e.g., how to handle cases like Acb * ArbMatrix except for defining separate functions for them)

Defining separate functions is definitely the correct way to do it. A pull request would be very appreciated 🙂

**Comment by nanleij** [comment]
I did a pull request; the only thing I am not sure about is whether to include AcbLike * ArbMatrixLike because it needs explicit conversion to an AcbMatrix/AcbRefMatrix
