### ISSUE TITLE
How can we enable multi-threaded Flint via Arblib.jl?

### ISSUE THREAD

**Issue by lucifer1004** [kalmarek/Arblib.jl#131]
Arb has a `flint_set_num_threads()` function to enable multi-threaded Flint, and Nemo.jl exposes this function, however, I do not see it in Arblib.jl.

**Comment by kalmarek** [comment]
It seems that this is flints function, not arblibs;

There is an env flag that needs to be set before loading `Flint_jll`, see
https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/blob/main/src/wrappers/x86_64-linux-gnu.jl
then we need to store the existence of this flag at `__init__` time and the thing will be a simple `ccall` to `libflint`.

@lucifer1004 mind making a PR?

**Comment by Joel-Dahne** [comment]
Closed by #132
