### ISSUE TITLE
Many allocations when calculating hypergeometric functions

### ISSUE THREAD

**Issue by lucifer1004** [kalmarek/Arblib.jl#139]
```julia
julia> @btime Arblib.hypgeom_bessel_jy!(Arb(0), Arb(0), Arb(10), Arb(1 // 100))
  47.990 μs (190 allocations: 14.17 KiB)
[2.691138339236344421096392716256098006835716550746321140061519723025122548483e-30 +/- 6.78e-106]
```

I cannot figure out why there are so many allocations on the Julia side.

**Comment by kalmarek** [comment]
185 of this allocations are happening in `arb` I believe. 
Also you probably should add `$`s in front of arguments to properly benchmark, since the time/allocation of arguments are added to the reported stats;

Other than this `hypgeom_bessel_jy!` just ccalls arb, so there's not much we can do I think.

**Comment by lucifer1004** [comment]
Sorry, I thought that allocations in `arb` would not be captured.

**Comment by Joel-Dahne** [comment]
Just to add to this, even though there's a large number of allocations the garbage collection time is very low. In this case less than 0.2%. This is the number to watch out for in general.
```
julia> @benchmark Arblib.hypgeom_bessel_jy!($(Arb(0)), $(Arb(0)), $(Arb(10)), $(Arb(1 // 100)))
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):   96.379 μs … 693.608 μs  ┊ GC (min … max): 0.00% … 82.28%
 Time  (median):      98.167 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   102.680 μs ±  17.409 μs  ┊ GC (mean ± σ):  0.16% ±  1.44%

  ▆█▄▃▃▃▂▂▁▁▁                                                   ▁
  ██████████████▇▇▆▆▇▇▆▆▆▇▆▅▅▆▄▄▄▃▄▅▅▄▄▃▄▄▃▅▄▅▄▃▄▄▂▃▄▅▅▅▅▅▅▇▆▇▇ █
  96.4 μs       Histogram: log(frequency) by time        178 μs <

 Memory estimate: 13.88 KiB, allocs estimate: 185.
```
