### ISSUE TITLE
Could you bump the Arb_jll version?

### ISSUE THREAD

**Issue by thofma** [kalmarek/Arblib.jl#147]

**Comment by kalmarek** [comment]
there are a few new functions added in 2.22:
https://arblib.org/history.html#version-2-22-0

@Joel-Dahne just bringing it to your attention, if you don't have time to update arbcalls, I can just bump Arb_jll version for now ;)

**Comment by Joel-Dahne** [comment]
I won't have time for a few days, so feel free to just bump the version!

**Comment by kalmarek** [comment]
#148

**Comment by thofma** [comment]
Thanks you guys!
