### ISSUE TITLE
Why Acb is not a subtype of Complex?

### ISSUE THREAD

**Issue by Jorispilot** [kalmarek/Arblib.jl#151]
I wonder why I get the following:
```julia
julia> Arb <: Real
true

julia> Arb <: AbstractFloat
true

julia> Acb <: Complex
false

julia> Acb <: Complex{AbstractFloat}
false

julia> VERSION
v"1.7.2"
```
Is this behavior on purpose, on is it a bug?

**Comment by Joel-Dahne** [comment]
`Complex{T}` is a concrete type with real and imaginary part having type `T`. In the case of `Acb` there is no distinct real and imaginary part, everything is stored together. If Julia had an `AbstractComplex` type then we would definitely want to have `Acb <: AbstractComplex`, however no such type exists. In fact the `Number` type in Julia is a bit weird, in base Julia it is often times interpreted as a complex value and in several cases it for example assumes commutativity of multiplication. But for example the `Quaternions.jl` package defines `Quaternion{T<:Real} <: Number` which is in no way a complex number and not commutative.

**Comment by Joel-Dahne** [comment]
More precisely you can only subtype abstract types and we have
```julia
julia> isabstracttype(Real)
true

julia> isabstracttype(Complex)
false
```

**Comment by Jorispilot** [comment]
I see. Thanks for the explanation. Using `Complex{Arb}` is fine for my code. I close the issue as there is obviously nothing to do.
