### ISSUE TITLE
Enable GitHub page for documentation

### ISSUE THREAD

**Issue by Joel-Dahne** [kalmarek/Arblib.jl#170]
The documentation seems to be building correctly now, it is available at the [gh-pages](https://github.com/kalmarek/Arblib.jl/tree/gh-pages) branch. I believe the next step is to point GitHub pages to this branch and I don't think I have access to this, so you would have to make the changes @kalmarek .  Following the [documentation](https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions) I found the description for how to do it [here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

**Comment by kalmarek** [comment]
@Joel-Dahne just in case You didn't notice, the webpage from `gh-pages` is up! ;)

**Comment by Joel-Dahne** [comment]
Fantastic!
