### ISSUE TITLE
Make sure that MPFR and Flint are built in thread safe mode

### ISSUE THREAD

**Issue by saschatimme** [kalmarek/Arblib.jl#19]
http://arblib.org/issues.html#thread-safety-and-caches

> Arb should be fully threadsafe, provided that both MPFR and FLINT have been built in threadsafe mode.

> Arb may cache some data (such as the value of π and Bernoulli numbers) to speed up various computations. In threadsafe mode, caches use thread-local storage.

I am not sure how the thread local caches play together with Julia threads but we should keep an eye on this later on (or ask Frederik to clarify)

**Comment by Joel-Dahne** [comment]
MPFR should be fine, Julia makes heavy use of it for BigFloats. Hopefully Flint does something similar, I believe they do, and then it should probably work.

**Comment by saschatimme** [comment]
> MPFR should be fine, Julia makes heavy use of it for BigFloats

You would think so, but https://github.com/JuliaLang/julia/issues/35796

**Comment by Joel-Dahne** [comment]
I guess I was to optimistic... Then we should keep an eye on this!

**Comment by kalmarek** [comment]
I was hoping for `LoadFlint` to take care of some of these considerations (in the future).

---
the solution with global precision (which I copied from julia MPFR) was not thread safe and we were aware of this, but it's good to keep this as a remainder. 
A cheap solution would be to wrap our version of precision with `Atomic` calls. A less user-friendly would be to always require `prec` argument in constructors.

But unlike `BigFloats` we are in position to make our own rules ;)

**Comment by saschatimme** [comment]
`precision` cannot be a thread-local global variable since then your algorithm would become completely out of sync if the scheduler decides to run tasks on different threads.
A single global variable (even atomic) is also just an accident waiting to happen.
So I think the only sane way to do this in library code is to explicitly give the precision for all ops resp. during construction provide the desired precision.

**Comment by saschatimme** [comment]
But for some quick code / scripts the global variable is completely fine. You should just not do this in library code 🙃

**Comment by kalmarek** [comment]
I guess this should be fixed by using jlls: #42

**Comment by saschatimme** [comment]
@kalmarek @Joel-Dahne Did any of you run multi-threaded Arblib.jl code so far? WIth this I mean running indepent Arb computations on multiple Julia threads, not threaded Arb operations.

I am trying to parallelize some code right now, and getting inconsistent errors that looks like something is not thread safe
