### ISSUE TITLE
Reconsider finalizer attachment

### ISSUE THREAD

**Issue by saschatimme** [kalmarek/Arblib.jl#23]
Currently `Arb`, `Arf`, etc.  look all like this

```julia
# c memory layout
struct arf_struct
    exponent::UInt      # fmpz
    size::UInt          # mp_size_t
    mantissa1::UInt     # mantissa_struct of length 128
    mantissa2::UInt
end

# mutable struct containing precision
mutable struct Arf <: Real
    arf::arf_struct
    prec::Int
   
   function Arf(si::Int64; prec::Integer=DEFAULT_PRECISION[])
        res = new(arf_struct(0,0,0,0), prec)
        init_set!(res, si)
        finalizer(clear!, res)
        return res
    end
end
```

In particular, the `Arf` struct is mutable since we need to attach a finalizer somewhere. We ended up with this design since this was the only design which only results in one allocation in Julia <= 1.4. Starting from Julia 1.5 however, it is possible to also have

```julia
# c memory layout
mutable struct arf_struct
    exponent::UInt      # fmpz
    size::UInt          # mp_size_t
    mantissa1::UInt     # mantissa_struct of length 128
    mantissa2::UInt

   function Arf(...)
        ... attach finalizer etc.
    end
end

# struct containing precision
struct Arf <: Real
    arf::arf_struct
    prec::Int
end
```
result in only one allocation. 
I think this design question is deeply tied together with how we want to handle indexing into Arb-owned matrices. Using the second approach, we can return an `Arf` without any extra allocations with the caveat that the memory lifetime is controlled by the matrix (but this is the same in C). Our current approach on the other hand would always trigger an allocation (either due to making a copy and attaching a finalizer, or constructing a new mutable struct).

Any thoughts?

**Comment by kalmarek** [comment]
If I remember correctly already 1.4 could elide the additional allocation (1.3 couldn't)

----
well, that's something of a challenge. Julia users will assume that
* `A[i,j]` does not allocate
* `a = A[i,j]` makes `a` outlive `A`.

It seems that without those assumptions using generic code with Arb matrices will be very fragile ?
Consider 
```julia
get_first(m::ArbMatrix) = m[1,1]

a,b = GC.@protect m
    a = get_first(m) # no allocation
    b = get_first(m) + 0  # creates new Arb
    a,b
end
```
here `a` holds garbage (`m` can be `GC`ed anytime after the block), but `b` is independent of `m`.

How about living up to those assumptions, but also providing syntax (ala `@view`?) to access Arb matrices without allocations?

**Comment by Joel-Dahne** [comment]
I think both avoiding extra allocations and allowing inplace operations on specific elements of the matrix. I'm not sure how this would work with inplace operations? How would for example
```
add!(get_first(m), get_first(m), 1)
```
work? Would this update `m` as expected?

In general I think this is the next big thing we have to figure out how to deal with at least. Whatever solution we solve it will probably work the same for anything containing Arb-pointers, so vectors and polynomials as well.

I think the most important thing is that we live up to the assumptions people have on how things work in Julia, and then as you say we can add special syntax if there are things we cannot handle in that way.

**Comment by saschatimme** [comment]
I like Mareks approach of being safe (and copy) by default and providing a macro to opt in to unsafe behavior. Inspiration can be https://github.com/JuliaArrays/UnsafeArrays.jl

**Comment by Joel-Dahne** [comment]
Would our ideas here also apply to how one would access the radius and midpoint of an `Arb`? An also the real and imaginary part of an `Acb`? For example you would like to be able to do things like `radius(x) < 1` without allocations and also do inplace operations of the respective parts.

**Comment by saschatimme** [comment]
Ugh 😫 I feel like it’s fine to have an unsafe radius by default otherwise I fear that things become really clunky :(

**Comment by Joel-Dahne** [comment]
It's unfortunate that the midpoint is stored before the radius in `arb_struct`, otherwise I think one possibility would be to define `Arb` as
```
mutable struct Arb <: Real
    radius::Mag
    midpoint::Arf
end
```
And let them have independent finalizers. `Arf` could in that case store it's own precision and the memory layout would be identical to our current solution. But since we need them in the opposite order we would get
```
mutable struct Arb <: Real
    midpoint::Arf
    radius::Mag
end
```
which doesn't have the same memory as

```
mutable struct Arb <: Real
    midpoint::arf_struct
    radius::mag_struct
    prec::Int
end
```
:(

**Comment by kalmarek** [comment]
we could still access those by implementing `unsafe_radius` using some low level machinery, like `pointer_from_objref` + `unsafe_wrap` + some pointer arithmetic :D I'm not sure I want to follow this path, though.

but @Joel-Dahne made another point:
how about defining `Arb` as `arf_struct + `mag_struct` (+ precision) and `Acb` as two `arb_structs` (+precision)? this way we have the same c-layout, but diverge from Arblib and we'd need to define out own `cconvert`s an maybe even `unsafe_convert`s which doesn't sound any better ;/

**Comment by kalmarek** [comment]
I like the approach of UnsafeArrays very much though!

**Comment by Joel-Dahne** [comment]
Why would this require use to define our own `cconvert`?
```
mutable struct Arb <: Real
    midpoint::arf_struct
    radius::mag_struct
    #arb::arb_struct
    prec::Int

    function Arb(;prec::Integer=DEFAULT_PRECISION[])
        res = new(arf_struct(0,0,0,0), mag_struct(0,0), prec)
        #res = new(arb_struct(0,0,0,0, 0,0), prec)
        init!(res)
        finalizer(clear!, res)
        return res
    end
end
```
Seems to work fine? Passes all the tests at least.

**Comment by kalmarek** [comment]
oh, interesting ;) that's even better ;) if the compiler is good enough at inlining this means we can have `radius(x)<1` without allocations then! (define the `Mag` constructor on `mag_struct` and hope that the actual constructor is elided)

**Comment by Joel-Dahne** [comment]
I thought I would try to see what happens if we try this with `Mag`, it should be easier since it has equivalent memory layout to `mag_struct`. My attempt was
```julia
mutable struct Arb <: Real
    midpoint::arf_struct
    radius::Mag
    #arb::arb_struct
    prec::Int

    function Arb(;prec::Integer=DEFAULT_PRECISION[])
        res = new(arf_struct(0,0,0,0), Mag(), prec)
        #res = new(arb_struct(0,0,0,0, 0,0), prec)
        init!(res.midpoint)
        finalizer(x -> clear!(x.midpoint), res)
        return res
    end
end
```
So my hope was that Julia would take caring of garbage collecting the radius when it goes out of scope. However I'm not so familiar with how the gc works in Julia and indeed something seems to go wrong, running the tests results in a segmentation fault
```
signal (11): Segmentation fault
in expression starting at /home/urathai/Syncthing/Work/Code/Arblib.jl/test/constructors-test.jl:1
gc_try_setmark at /home/urathai/Sources/julia/src/gc.c:1554 [inlined]
gc_mark_scan_obj8 at /home/urathai/Sources/julia/src/gc.c:1704 [inlined]
gc_mark_loop at /home/urathai/Sources/julia/src/gc.c:1971
_jl_gc_collect at /home/urathai/Sources/julia/src/gc.c:2703
...
```

**Comment by kalmarek** [comment]
but this `Arb` is not binary compatible with the c one: https://docs.julialang.org/en/v1/devdocs/object/
`Mag` is 2 bytes (iirc) larger than `mag_struct` since in contains 'metadata' header. This is why we have `Base.unsafe_convert` to shift the pointer from julia struct to compatible one
