### ISSUE TITLE
Auto export all defined functions

### ISSUE THREAD

**Issue by saschatimme** [kalmarek/Arblib.jl#33]
Should we automatically add an `export` statement for each generated function in `arbcall`? I would say yes. This makes it much more convenient to write a one-off script using the library

**Comment by Joel-Dahne** [comment]
I'm not sure how we should handle this. I'm worried that it would clutter the namespace a bit to much. You would get a lot of collisions with other packages I feel. My idea have been that we mainly export cleaned up versions of the generated functions and make sure to make them extensions to already existing methods. For example we will probably want to import a lot of methods from `SpecialFunctions.jl` in the end.

Bot I'm far from sure about the best way to handle this...

**Comment by kalmarek** [comment]
Understandably it's a pain right now to write a script with `Arblib`s all over the place. 

On the other hand I'd rather not export everything what we define in the long run for precisely the same reason @Joel-Dahne raised: it's way too much generated content to have control on what collides with what in which package

**Comment by saschatimme** [comment]
Okay fair point. So this will be some fun manual work.

**Comment by Joel-Dahne** [comment]
Actually I have been looking forward to doing this manual work 😂. I wanted to have all basic types handled first. Which we will soon have hopefully!
