### ISSUE TITLE
len detection in arbcall is broken

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/Arblib.jl#55]
this commit broke it:
https://github.com/kalmarek/Arblib.jl/commit/57fff067ab8eab62bf1b0e5b45f5d15fc8582aea
@saschatimme can you explain what was the reason to remove `Ptr{arb_struct}` from `jltype(ca::Carg{ArbVector})` (and the same for `AcbVector`? (I really need to undust my memory about the function of all of those `Unions`...)

In any case https://github.com/kalmarek/Arblib.jl/blob/dc8743597a5ea1d2c6eeb76d360db1d7c706516e/src/arbcall.jl#L198
needs to be kept in sync with `jltype`

also: none of the tests caught it; we need to add
```julia
            (
                "int _acb_vec_is_zero(acb_srcptr vec, slong len)",
                [
                    :(vec::$(Union{AcbVector, Arblib.acb_vec_struct})),
                ],
                [
                    Expr(:kw, :(len::Integer), :(length(vec)))
                ]
            )
```
to `jlargs` testset.

**Comment by saschatimme** [comment]
I think I hit some method ambiguities, but I will look into this tomorrow

**Comment by kalmarek** [comment]
@Joel-Dahne since you take care of the `arbcall"..."` generations I found these signatures:
```julia
arbcall"void _arb_vec_neg(arb_ptr B, arb_srcptr A, slong n)"
arbcall"void _arb_vec_sub(arb_ptr C, arb_srcptr A, arb_srcptr B, slong n, slong prec)"
arbcall"void _arb_vec_add(arb_ptr C, arb_srcptr A, arb_srcptr B, slong n, slong prec)"
``` 
that need to be amended (`n` → `len`) for out codegen to work;
