### ISSUE TITLE
Make a first release

### ISSUE THREAD

**Issue by saschatimme** [kalmarek/Arblib.jl#60]
I think we are getting to a point where we can have a first release.

- [x] Merge #32
- [x] Merge #61 
- [x] Merge #54
- [x] Merge #57
- [x] Merge #59 
- [x] Create a README outlining our conversion strategy and introducing the types

@kalmarek @Joel-Dahne please amend the list with the things you have in mind.

**Comment by Joel-Dahne** [comment]
I have been quite busy this last week so have not had to much time to follow everything you are doing. But great that you are getting things done! Unfortunately I'm to invested in Nemo for my current project so I'll not be able to switch to Arblib yet. Hopefully I'll start my next project in the end of this semester and then I can maybe make the switch. That would allow me to try out the things a bit more and test the interfaces.

By release do you mean adding it to the Julia package repo? I don't think we are ready for a 1.0 release quite yet, but making a 0.3.0 release and then following the semantic versioning should be fine!

- [ ] After merging #32 and finishing the refactoring we can add parsing of more Arb files `hypgeom` among others
- [ ] We should probably add more documentation for many of the methods

There is also more work I want to do on the polynomials and series, but that can also wait.

**Comment by saschatimme** [comment]
Oh yes, I didn't intend to have a 1.0 release, but a 0.x. I want to ship a certification feature in HomotopyContinuation.jl and for this I need a proper release (things are already working).

**Comment by saschatimme** [comment]
We can also make a first release without #32 if you want to have some time to play with these since neither @kalmarek  nor myself need this at the moment.

**Comment by Joel-Dahne** [comment]
I think merging #32 first makes sense, then we have all of the basic datatypes from Arb included. If you fix the refactoring of `arbcall` then I can make the necessary adjustments for the polynomials, I should be able to get it done in the weekend, and also add more parsed methods, which should be fairly quick.

**Comment by kalmarek** [comment]
what I'd like to see is general `rand` interface, so that we can `rand(Arb)`, `rand(Acb(0), 5) (should it be `AcbVector`?) etc.

**Comment by saschatimme** [comment]
@kalmarek @Joel-Dahne do you consider the RNG interface a blocker for the release? Or do you think we could make a quite first release after we created some documentation?

**Comment by Joel-Dahne** [comment]
I don't think it's required for the release, but would be a nice addition to the one after. Some more documentation and in particular writing in the README that we are missing a lot of documentation is the main thing missing I think. The integration is almost done I feel, so that might be worth it to wait for.

**Comment by Joel-Dahne** [comment]
Well done!
